college_conversion_list: dict[str, str] = {
    "Michigan": "MI",
    "Miami, O.": "OH",
    "Arkansas": "AR",
    "California": "CA",
    "Harvard": "MA",
    "UCLA": "CA",
    "Louisiana State": "LA",
    "Boston College": "MA",
    "Virginia Tech": "VA",
    "San Diego": "CA",
    "Texas Tech": "TX",
    "Georgia": "GA",
    "Alabama": "AL",
    "Ohio State": "OH",
    "South Carolina": "SC",
    "Rutgers": "NJ",
    "Troy": "AL",
    "Michigan State": "MI",
    "Nebraska": "NE",
    "Oklahoma": "OK",
    "Florida": "FL",
    "South Florida": "FL",
    "Iowa": "IA",
    "Texas Christian": "TX",
    "Indiana": "IN",
    "Arizona": "AZ",
    "East Carolina": "NC",
    "Southern Methodist": "TX",
    "Kentucky": "KY",
    "Citadel": "SC",
    "Southern California": "CA",
    "Central Michigan": "MI",
    "Rice": "TX",
    "Texas State": "TX",
    "Texas A&M": "TX",
    "Missouri": "MO",
    "Wisconsin": "WI",
    "North Carolina": "NC",
    "Purdue": "IN",
    "Colorado": "CO",
    "Pittsburgh": "PA",
    "Notre Dame": "IN",
    "Florida State": "FL",
    "Mississippi State": "MS",
    "Tennessee": "TN",
    "Eastern Washington": "WA",
    "Stanford": "CA",
    "Marshall": "WV",
    "Cincinnati": "OH",
    "Arizona State": "AZ",
    "Kansas": "KS",
    "Auburn": "AL",
    "Syracuse": "NY",
    "Illinois": "IL",
    "North Alabama": "AL",
    "Utah State": "UT",
    "Vanderbilt": "TN",
    "Boise State": "ID",
    "Nevada": "NV",
    "Fresno State": "CA",
    "Brigham Young": "UT",
    "Georgia Tech": "GA",
    "Clemson": "SC",
    "Louisiana Tech": "LA",
    "Duke": "NC",
    "North Carolina State": "NC",
    "Texas-El Paso": "TX",
    "Western Kentucky": "KY",
    "Oregon State": "OR",
    "Idaho": "ID",
    "Army": "NY",
    "Central Florida": "FL",
    "Connecticut": "CT",
    "Colorado State-Pueblo": "CO",
    "Northwestern": "IL",
    "South Carolina State": "SC",
    "James Madison": "VA",
    "Old Dominion": "VA",
    "Florida Atlantic": "FL",
    "Alabama-Birmingham": "AL",
    "California-Irvine": "CA",
    "California, Pa.": "PA",
    "Western Michigan": "MI",
    "Louisiana-Lafayette": "LA",
    "Southern Mississippi": "MS",
    "North Carolina-Charlotte": "NC",
    "Hawaii": "HI",
    "Liberty": "VA",
    "Utah": "UT",
    "No College": None
}
